##### ################################################################
#####
#####  RUN
#####  ===
#####   docker-compose up -d
#####   docker-compose stop
#####   docker-compose rm
#####   docker-compose ps
#####
#####  + - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - +
#####  : Docker Compose                                                              :
#####  :                                                                             :
#####  :   +---------------+      +----------------------------------------------+   :     +-------------------+
#####  :   | web           |      | api                                          |   :     | Database          |
#####  :   |  +-------+    |      |  +------------------+   +----------------+   |   :     |  +------------+   |
#####  :   |  | nginx |<------------>| woo(stroborihts) |<->| glpgs-hooligan |<-------------->| postgresql |   |
#####  :   |  +-------+    |      |  +------------------+   +----------------+   |   :     |  +------------+   |
#####  :   |               |      |                                              |   :     |                   |
#####  :   |               |      |                                              |   :     |                   |
#####  :   |               |      |                                              |   :     |                   |
#####  :   +---------------+      +----------------------------------------------+   :     +-------------------+
#####  :                                                                             :
#####  + - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - +
#####
##### ################################################################
version: '3'
services:

  ter.webfront:
    build: ./
    image: nginx
    container_name: ter-webfront
    restart: always
    ports:
      - 8080:80
    volumes:
      - /some/content:/usr/share/nginx/html:ro

  ter.api-and-db:
    build: ./
    image: ter.api
    container_name: ter-api-and-db
    restart: always
    ports:
      - 55559:55555
    tty: true
    # 必要な時だけ利用する。
    # environment:
    #   API_PORT : ${TER_API_PORT}
    #   API_SESSION_NAME : ${TER_API_SESSION_NAME}
    #   DIR_GRAPH_COMMON : ${TER_DIR_GRAPH_COMMON}
    #   DIR_GRAPH_CAMPUS : ${TER_DIR_GRAPH_CAMPUS}
    #   DIR_GRAPH_SCHEMA : ${TER_DIR_GRAPH_SCHEMA}
    volumes:
      - "/Users/satoshi.iwasaki/var/ter/graph/common:/home/cl_user/var/ter/graph/common"
      - "/Users/satoshi.iwasaki/var/ter/graph/campus:/home/cl_user/var/ter/graph/campus"
      - "/Users/satoshi.iwasaki/var/ter/graph/schema:/home/cl_user/var/ter/graph/schema"
