##### ################################################################
#####
#####  RUN
#####  ===
#####   docker-compose up -d
#####   docker-compose stop
#####   docker-compose rm
#####   docker-compose ps
#####
#####  + - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - +
#####  : Docker Compose                                                              :
#####  :                                                                             :
#####  :   +---------------+      +----------------------------------------------+   :     +-------------------+
#####  :   | web           |      | api                                          |   :     | Database          |
#####  :   |  +-------+    |      |  +------------------+   +----------------+   |   :     |  +------------+   |
#####  :   |  | nginx |<------------>| woo(stroborihts) |<->| glpgs-hooligan |<-------------->| postgresql |   |
#####  :   |  +-------+    |      |  +------------------+   +----------------+   |   :     |  +------------+   |
#####  :   |               |      |                                              |   :     |                   |
#####  :   |               |      |                                              |   :     |                   |
#####  :   |               |      |                                              |   :     |                   |
#####  :   +---------------+      +----------------------------------------------+   :     +-------------------+
#####  :                                                                             :
#####  + - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - +
#####
##### ################################################################
version: '3'
services:

  ter.api:
    image: renshi/ter.api
    container_name: ter-api
    restart: always
    ports:
      - 55555:55555
    tty: true
    environment:
      API_PORT : 55555
      API_SESSION_NAME : session.ter
      DIR_GRAPH_COMMON : /home/cl_user/var/ter/graph/common
      DIR_GRAPH_CAMPUS : /home/cl_user/var/ter/graph/campus
      DIR_GRAPH_SCHEMA : /home/cl_user/var/ter/graph/schema
    volumes:
      - ${PWD}/docker/data/graphs/common:/home/cl_user/var/ter/graph/common
      - ${PWD}/docker/data/graphs/campus:/home/cl_user/var/ter/graph/campus
      - ${PWD}/docker/data/graphs/schema:/home/cl_user/var/ter/graph/schema

  ter.web:
    image: renshi/ter.front
    container_name: ter-front
    restart: always
    ports:
      - 8080:80
    environment:
      API_SCHEME : http
      API_HOST : localhost
      API_PORT : 8080
      API_path : /api/v1
    links:
      - ter.api
