(in-package :ter.api.controller)

(defun find-ter ()
  (let ((graph ter.db:*graph*))
    (list :nodes (nconc '()
                        (ter:find-resource graph)
                        (ter:find-event graph)
                        (ter:find-correspondence graph)
                        (ter:find-comparative graph)
                        (ter:find-recursion graph)
                        (ter:find-attribute graph)
                        (ter:find-attribute-instance graph)
                        (ter:find-identifier graph)
                        (ter:find-identifier-instance graph))
          :edges (ter:find-ter-all-edges graph))))
